### ISSUE TITLE
Scrambler

### ISSUE THREAD

**Issue by d1ckofsheep** [KamuiKody/k-ui#1]
There is issue with scrambler hackgame.
When you open that hack it's only cursor on middle of screen.

**Comment by KamuiKody** [comment]
im looking into this now thank you for the insight :)

**Comment by KamuiKody** [comment]
i am unable to recreate this issue please be sure you are on the most up to date copy

**Comment by d1ckofsheep** [comment]
> i am unable to recreate this issue please be sure you are on the most up to date copy

i fixed it by adding back (old) from ps , on your version only this not working.

**Comment by KamuiKody** [comment]
do you get any errors when trying to do the scrambler?
